fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    inifile: "https://github.com/puppetlabs/puppetlabs-inifile.git"
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    archive: "https://github.com/puppet-community/puppet-archive.git"
  symlinks:
    rundeck: "#{source_dir}"
