---
sudo: false
dist: trusty
language: ruby
cache: bundler
addons:
  apt:
    packages:
      - libaugeas-dev
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 2.4.2
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-16.04 CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.4.2
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-7 CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.4.2
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/debian-8 CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.1.9
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 4.0" CHECK=test
  - rvm: 2.4.2
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=test_with_coveralls
  - rvm: 2.4.2
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=rubocop
  - rvm: 2.4.2
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
branches:
  only:
  - master
  - /^v\d/
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: "ExSbFQsxOlpFTc/4TTGJElIx0/sYNZ1I2Nbd9EfGPNeECXBgmqTdJmPqdV6cl3mKDFh+tSSxnIDZe5BILhmxIR7aF2lbf8jwcbo2nxe9qAZ42GDKNV2klNXUjR7kA7tz220RNO9rM3HDKAwrKtCPtwQ0Q5u90YGGJDj2nr7NUaM="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"
